name: VIAPI
version: 3.1.0
authors: [VadamDev, Java_Implements, Estxbxn]
description: A huge toolkit for plugin developers
website: https://github.com/VadamDev/VIAPI

main: net.vadamdev.viapi.internal.VIAPIPlugin
load: STARTUP