name: VIAPI
version: 3.0.1
authors: [VadamDev, Java_Implements]
description: A huge toolkit for plugin developers
website: https://github.com/VadamDev/VIAPI

main: net.vadamdev.viapi.internal.VIAPIPlugin
load: STARTUP